#!/bin/sh

versionFile="version_$(git branch | sed -n -e 's/^\* \(.*\)/\1/p').properties"
cd ".git/hooks"
javac Version.java
java -cp . Version "../../version/$versionFile" 0
rm -rf Version.class
cd "../.."
git add "$versionFile"
